filetype plugin indent on
set background=dark
syntax enable

set encoding=utf8
set title
set nu
set relativenumber
set nowrap
set ignorecase
set smartcase
set incsearch
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set wildmenu
set noswapfile
set undodir=~/.vim/undodir
set undofile
set clipboard=unnamedplus

let mapleader = " " " map leader to Space

nnoremap <C-c> yy
inoremap <C-c> yy
vnoremap <C-c> yy

inoremap jk <esc>
nnoremap E $
nnoremap J <NOP>

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
"inoremap <Up> <NOP>
"inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

" inoremap ( ()<Esc>i
" inoremap { {}<Esc>i
" inoremap [ []<Esc>i
inoremap {<CR> {<CR>}<Esc>ko<tab>
inoremap < <><Esc>i
" inoremap ' ''<Esc>i
" inoremap " ""<Esc>i

" nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-t> :NERDTree<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" fzf
map <C-p> :Files<CR>
nmap <leader>; :Buffers<CR>

"quick save
nmap <leader>w :W<CR>

nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz

command W w
command Wq wq

call plug#begin()

Plug 'base16-project/base16-vim'

Plug 'dense-analysis/ale'
Plug 'rust-lang/rust.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'

Plug 'airblade/vim-rooter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()            

let g:NERDTreeWinSize=25
" let g:NERDTreeDirArrowExpandable = '+'
" let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeHighlightFolders = 1 " enables folder icon highlighting using exact match
let g:NERDTreeHighlightFoldersFullName = 1 " highlights the folder name

" for normal alacritty sessions
let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
set t_Co=256
let base16colorspace=256  " Access colors present in 256 colorspace
" colorscheme base16-gruvbox-dark-hard
colorscheme base16-atelier-dune
set termguicolors

" let g:airline_powerline_fonts = 1
let g:airline_extensions = []
" let g:airline_theme='base16-gruvbox-dark-hard'


" for tmux sessions
if &term =~ '256color'
  " Enable true (24-bit) colors instead of (8-bit) 256 colors.
  " :h true-color
  if has('termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
  endif
  " colorscheme base16-atelier-dune
  colorscheme base16-gruvbox-dark-hard
endif

let s:brown = "905532"
let s:aqua =  "3AFFDB"
let s:blue = "689FB6"
let s:darkBlue = "44788E"
let s:purple = "834F79"
let s:lightPurple = "834F79"
let s:red = "AE403F"
let s:beige = "F5C06F"
let s:yellow = "F09F17"
let s:orange = "D4843E"
let s:darkOrange = "F16529"
let s:pink = "CB6F6F"
let s:salmon = "EE6E73"
let s:green = "8FAA54"
let s:lightGreen = "31B53E"
let s:white = "FFFFFF"
let s:rspec_red = 'FE405F'
let s:git_orange = 'F54D27'
